version: '3.1'

services:
    db:
        image: mysql:5.7
        ports:
            - '3306:3306'
        restart: 'always'
        environment:
            MYSQL_DATABASE: 'resenhas'
            MYSQL_USER: 'resenhas'
            MYSQL_PASSWORD: '123456'
            MYSQL_ROOT_PASSWORD: '123456'

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
