"""empty message

Revision ID: 7c6b6e0fb433
Revises: f674faa11db8
Create Date: 2019-10-19 15:34:55.105982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6b6e0fb433'
down_revision = 'f674faa11db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artigos', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artigos', type_='foreignkey')
    op.drop_column('artigos', 'user_id')
    # ### end Alembic commands ###
